<?php
session_start();
include_once('db_credentials.php');
$code = $_POST['code'];
//code that was generated by the system
$generatedcode = $_POST['generatedcode'];
$newPass = $_POST['password'];
$confirmPass = $_POST[''];
$email = $_POST['email'];
$user_type = $_POST['user_type'];

if($code == $generatedcode){
  $conn = OpenCon();
  $sql = null;

  if(0 == $user_type){
    $sql = "UPDATE Admin SET password = '$newPass' WHERE email = '$email'";
  }
  if(1 == $user_type){
    $sql = "UPDATE Employer SET password = '$newPass' WHERE email = '$email'";
  }
  if(2 == $user_type){
    $sql = "UPDATE User SET password = '$newPass' WHERE email = '$email'";
  }

  $result = $conn -> query($sql)or die(mysqli_error($conn));

  //echo 'code : ' . $code . 'new pass: ' . $newPass . 'email: ' . $email . 'user type : ' . $user_type;
}else{
  $_SESSION['errmsg'] = 'Invalid code';
  /*echo "<script type='text/javascript'>
        window.location.href = 'passwordRecoveryProcess.php';
        </script>";*/
  //echo  'session code: ' . $generatedcode . ' code : ' . $code . ' new pass: ' . $newPass . ' email: ' . $email . ' user type : ' . $user_type;
  exit();
}
echo "<script type='text/javascript'>
      window.location.href = 'login.php';
      </script>";
 ?>
